# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('macro-central', ['thz'])
    obj.source = 'macro-central.cc'

    obj = bld.create_ns3_program('nano-adhoc', ['thz'])
    obj.source = 'nano-adhoc.cc'
